name: carconnect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.2
  awesome_notifications: ^0.7.4+1
<<<<<<< HEAD
  google_fonts: ^4.0.4
=======
  google_fonts: ^6.1.0
>>>>>>> origin/main
  http: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
<<<<<<< HEAD
  provider: ^6.1.1
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  geocoder2: ^1.4.0
  flutter_geofire: ^2.0.3
  location: ^5.0.3
  flutter_polyline_points: ^1.0.0
=======
  flutter_map: ^6.1.0
  provider: ^6.1.1
  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^2.0.0
>>>>>>> origin/main
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/