# Generated by Django 4.2.5 on 2024-01-06 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenderChoices",
        ),
    ]
