# Generated by Django 4.2.5 on 2024-01-06 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_delete_genderchoices"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="ServiceUser",
        ),
    ]
