# Generated by Django 4.2.5 on 2024-01-06 06:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_user_serviceuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceuser",
            name="contact_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
