# Generated by Django 4.2.5 on 2024-01-06 06:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_serviceuser_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceuser",
            name="username",
            field=models.CharField(
                max_length=18, unique=True, validators=[api.models.validate_username]
            ),
        ),
    ]
