# Generated by Django 4.2.5 on 2024-01-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_serviceuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                ("requestId", models.BigAutoField(primary_key=True, serialize=False)),
                ("presenet_loc_longitude", models.FloatField()),
                ("presenet_loc_latitude", models.FloatField()),
                ("destination_loc_longitude", models.FloatField()),
                ("destination_loc_latitude", models.FloatField()),
                ("isDeleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="serviceuser",
            name="destination_loc_latitude",
        ),
        migrations.RemoveField(
            model_name="serviceuser",
            name="destination_loc_longitude",
        ),
        migrations.RemoveField(
            model_name="serviceuser",
            name="id",
        ),
        migrations.AddField(
            model_name="serviceuser",
            name="uid",
            field=models.BigAutoField(default="1", primary_key=True, serialize=False),
        ),
    ]
