# Generated by Django 4.2.5 on 2024-01-06 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_servicerequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="username",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.serviceuser",
            ),
        ),
    ]
