# Generated by Django 4.2.5 on 2024-01-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_servicerequest_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceuser",
            name="uid",
            field=models.AutoField(default="1", primary_key=True, serialize=False),
        ),
    ]
