# Generated by Django 4.2.5 on 2024-01-06 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_serviceuser_uid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicerequest",
            old_name="username",
            new_name="user",
        ),
    ]
