# Generated by Django 4.2.5 on 2024-01-08 09:09

import api.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_rename_username_servicerequest_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("uid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[api.models.validate_username],
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("presenet_loc_longitude", models.FloatField()),
                ("presenet_loc_latitude", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="user",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
        migrations.DeleteModel(
            name="ServiceUser",
        ),
    ]
